! PROGRAM TO PLOT FROM RAW HISTOGRAM FILE
! AUTHOR, ABHIJIT BAISHYA
! FIRST EDIT: 04/10/2021
! LAST EDIT: 01/02/2022


program histToGraph 
   use hist_mod
   implicit none
   
   
   real,allocatable :: hist(:),gr_hist(:,:)
   character(50) :: inname,outname,LowerLimit,UpperLimit,NumberOfBins,gpname,response
   real :: lowlim,uplim,binsize
   integer :: i,N,nbins,iostat
   
   ! CHECK FOR PROPER INPUT FORMAT AT THE TERMINAL, I.E. EITHER THE INPUT FILE HAS TO BE GIVEN, 
   ! IN WHICH CASE THE OUTPUT FILE WILL BE GENERATED BY THE PROGRAM OAND PARAMETERS FOR THE HISTOGRAM
   ! WILL BE CALCULATED AUTOMATICALLY OR PARAMTERES CAN BE EXPLICITELY GIVEN
   if (iargc() < 1 .or. iargc() > 4) then 
      print*,'Input format is "./program inputfile" or "./program inputfile LowerLimit UpperLimit NumberOfBins"'
      stop
   endif 
   
   ! ASSIGNING INPUT FILE AND OUTPUT FILE NAMES TO VARIABLES
   if (iargc() == 1) then 
      call getarg(1,inname)
      outname = 'graph_'//TRIM(inname)
   elseif (iargc() == 2) then 
      call getarg(1,inname)
      outname = 'graph_'//TRIM(inname)
      call getarg(2,LowerLimit)
      read(LowerLimit,*)lowlim
   elseif (iargc() == 3) then
      call getarg(1,inname)
      outname = 'graph_'//TRIM(inname)
      call getarg(2,LowerLimit)
      call getarg(3,UpperLimit)
      read(LowerLimit,*)lowlim
      read(UpperLimit,*)uplim
   elseif (iargc() == 4) then
      call getarg(1,inname)
      outname = 'graph_'//TRIM(inname)
      call getarg(2,LowerLimit)
      call getarg(3,UpperLimit)
      call getarg(4,NumberOfBins)
      read(LowerLimit,*)lowlim
      read(UpperLimit,*)uplim
      read(NumberOfBins,*)nbins
   endif 

   ! GNUPLOT FILE FOR PLOTTING
   gpname='gp_hist.gp'
   
   ! OPENING FILES FOR READING AND WRITING 
   open(10,file=inname,action='read')      ! OPENING INPUT HISTOGRAM FILE
   open(11,file=outname,action='write')    ! OPENING OUPUT GRAPH FILE
   open(12,file=gpname,action='write')
   
   N = 0 ! NUMBER OF LINES
   do    
      read(10,*,iostat=iostat)
      if (iostat < 0) exit
      N=N+1
   enddo 
   
   ! ALLOCATING THE HISTOGRAM ARRAY
   allocate(hist(N))  
   
   rewind(10)  ! REWINDING FILE FROM EOF TO THE BEGINNING
   
   ! READING DATA POINTS FROM HISTOGRAM FILE
   do i=1,N
      read(10,*)hist(i)
   enddo 


   ! ASSIGNING INPUT FILE AND OUTPUT FILE NAMES TO VARIABLES
   if (iargc() == 1) then 
      call opt_binw(hist,binsize)
      lowlim = minval(hist)
      uplim = maxval(hist) 
      nbins = nint((uplim-lowlim)/binsize)
      !print*,binsize,lowlim,uplim,nbins
      ! CALLING HIST_TO_GRAPH SUBROUTINE TO CONVERT HISTOGRAM TO GRAPH
      call hist_to_graph(hist,nbins,lowlim,uplim,gr_hist)
   elseif (iargc() == 2) then 
      call opt_binw(hist,binsize)
      uplim = maxval(hist) 
      nbins = nint((uplim-lowlim)/binsize)
      !print*,lowlim,uplim,nbins
      ! CALLING HIST_TO_GRAPH SUBROUTINE TO CONVERT HISTOGRAM TO GRAPH
      call hist_to_graph(hist,nbins,lowlim,uplim,gr_hist)
   elseif (iargc() == 3) then
      call opt_binw(hist,binsize)
      nbins = nint((uplim-lowlim)/binsize)
      !print*,lowlim,uplim,nbins
      ! CALLING HIST_TO_GRAPH SUBROUTINE TO CONVERT HISTOGRAM TO GRAPH
      call hist_to_graph(hist,nbins,lowlim,uplim,gr_hist)
   elseif (iargc() == 4) then
      !print*,lowlim,uplim,nbins
      ! CALLING HIST_TO_GRAPH SUBROUTINE TO CONVERT HISTOGRAM TO GRAPH
      call hist_to_graph(hist,nbins,lowlim,uplim,gr_hist)
   endif
   

   ! WRITING GRAPH X,Y DATA INTO FILE
   do i=1,nbins+1
       write(11,*)gr_hist(i,:)
   enddo 
   
   ! GENERATING GNUPLOT FILE FOR PLOTTING 
   !write(12,*)'set term qt'
   write(12,*)'set xrange[',lowlim,':',uplim,']'
   write(12,*)'plot "',trim(outname),'" u 1:2 sm csplines' ! SPLINE CURVE WILL BE PLOTTED, IF YOU WANT USUAL LINE PLOT OR SCATTER PLOT, EDIT THIS LINE
   
   ! CLOSING OPEN FILES
   close(10)
   close(11)
   close(12)
   
   ! DEALLOCATING THE HIST ARRAY TO FREE MEMORY
   deallocate(hist,gr_hist)
   
   ! PLOTTING COMMAND
   !print*,'Whether you want to plot the histogram? Y/N?'
   call execute_command_line('gnuplot -p gp_hist.gp')

   
   ! REMOVING OUTPUT GRAPH FILE, COMMENT OUT IF YOU NEEDED
   print*,'Do you want to delete the ouput graph file? Y/N?'
   
   do 
   read*,response 
   if (response == 'Y' .or. response == 'y') then 
      call execute_command_line('rm '//outname)
      exit 
   elseif (response == 'N' .or. response == 'n') then 
      exit 
   else 
      print*,'Enter a valid command, e.g. Y/N'
   endif 
   enddo 
   
   ! REMOVING GNUPLOT FILE, COMMENT OUT IF NEEDED
   call execute_command_line('rm gp_hist.gp')
   
end program
